"""add User and Role

Revision ID: 10d4c87c9153
Revises: None
Create Date: 2015-09-19 14:06:07.772000

"""

# revision identifiers, used by Alembic.
revision = '10d4c87c9153'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
