"""User signature migration

Revision ID: 1bf107f6a07d
Revises: 10d4c87c9153
Create Date: 2015-09-21 21:50:32.979000

"""

# revision identifiers, used by Alembic.
revision = '1bf107f6a07d'
down_revision = '10d4c87c9153'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
